name: Lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    phpcs:
        name: PHPCS

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: PHPCS check
              uses: chekalsky/phpcs-action@v1

    tlint:
        name: TLint

        continue-on-error: false

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction --no-progress

            - name: Run Tlint
              run: vendor/bin/tlint
